### ISSUE TITLE
PS submission using Jupyter notebook?

### ISSUE THREAD

**Issue by bobaekang** [rickecon/StructEst_W17#12]
Good morning, Dr. Evans @rickecon 

I have noticed that other people are submitting their work using the Juypter Notebook format while I just wrote and uploaded my codes in the Python script format. Are we expected to use Jupyter Notebook for homework submission? Also, are we expected to submit the pdf document using the LaTex as well? Thank you!

**Comment by rickecon** [comment]
For submitting problem sets, I prefer a Python script and a LaTeX-PDF document. But I will also accept Jupyter notebook submissions. Jupyter notebooks are easier for me to grade. But Python scripts are more valuable for you and your personal toolbox. It is for that latter reason that I prefer the script-and-LaTeX-PDF method. @bobaekang
