### ISSUE TITLE
PS3 setup clarification

### ISSUE THREAD

**Issue by olivianatan** [rickecon/StructEst_W17#18]
Dr Evans-
I have a quick clarification question on the setup. It says: "Assume that $z_0 = \mu$ so that $z_1 = \mu$. I just wanted to clarify that this should be $z_1 = \mu + \epsilon_1$? 
Thanks,
Olivia

**Comment by rickecon** [comment]
@olivianatan It is equivalent. The general equation is:

z_t = rho * z_{t-1} + (1 - rho) * mu + eps_t

If z_0 = mu, then z_1 = mu + eps_t by the equation above.
